### ISSUE TITLE
Vita3k crashing when opening Dengeki Bunko: Fighting Climax

### ISSUE THREAD

**Issue by Derpfestor21** [Vita3K/Vita3K-Android#162]
Dengeki Bunko: Fighting Climax crashes when open dispite it working fine on pc

**Comment by GreenLantern03** [comment]
Android.apk
Lasted build (last week released).
Device:
Anbernic rg405m.

GamePlay works 👍. My issue that the “main menu” Text or words like settings & versus sometimes disappeared or flicker.
