### ISSUE TITLE
Game's won't download 

### ISSUE THREAD

**Issue by Rylie12** [Vita3K/Vita3K-Android#192]
![Screenshot_2023-02-15-22-41-08-197_org vita3k emulator](https://user-images.githubusercontent.com/96661334/219059290-96648586-5689-4e2e-9d81-66b28baf123c.jpg)

**Comment by Shahbaz0007** [comment]
Same problem

**Comment by Shahbaz0007** [comment]
Can't install any one games install

**Comment by Fizx-gnes** [comment]
Yes Same problem

**Comment by joelolopez** [comment]
working as intended thia should be close

**Comment by Rylie12** [comment]
So do i download games
