### ISSUE TITLE
Version 3 crashing after installing gpu driver

### ISSUE THREAD

**Issue by usernamecreative08** [Vita3K/Vita3K-Android#258]
to be more specific, when i reopen the app after installing said drivers, the app crashes everytime

**Comment by maestrosistema** [comment]
Delete "config.yml" found inside: 

android/data/org.vita3k.emulator/files

**Comment by usernamecreative08** [comment]
> Delete "config.yml" found inside:
> 
> android/data/org.vita3k.emulator/files
