### ISSUE TITLE
v4 doesn't work 

### ISSUE THREAD

**Issue by knjazeva** [Vita3K/Vita3K-Android#297]
I have MediaTek Helio G95 with 6gb of ram.The app launches but when try to get in a game it crashes  immediately. Maybe it a problem with the game a tryed (Persona 4 Golden) but it worked fine with v3.

**Comment by Trixarian** [comment]
Try turning off Settings--->GPU---> Enable memory mapping, and restart the app. This option doesn't seem to like the Mali GPU much
