### ISSUE TITLE
Do developers even care about reported issues?

### ISSUE THREAD

**Issue by HFPasfho** [Vita3K/Vita3K-Android#362]
I noticed that issues in Vita3K-Android repo get virtually no attention from the dev team. It looks like they are unwanted. I have to admit that many of them really don't add anything like "fix fifa asap pliz" or "no working" but writing an actual quality issue report seems so pointless. Gathering as much details as possible about some issues only for no one to read it.

I get it's a lot of work with a project like this. This is a normal question with no overtone, don't look at it as a grievance. Just want to know because issues aren't addressed, garbage reports aren't closed, nothing really happens here and it makes me worried.

**Comment by Macdu** [comment]
Hello, to be honest I don't look at the issues for many reasons:

- First indeed a lot of the issues are pointless, just the title and sometime one phrase "Pls fix my game", it doesn't really help and I kind of agree that this repository needs to be better moderated, but nobody has the time for it.
- The android version still needs a lot more fixes and I already know what I need to improve. Like I know about the texture issue on Mali GPU and (fortunately) have an idea of how to fix. Reading 10 different issues on it won't help me any more. When the android version will be in a better state I will look more at the issues to get ideas on what to do next.
- I only have one phone which is my personal phone (poco F3 on Android 12), it is really hard to fix Android 10 issues or issues that I can't replicate.

So well that basically sums it.

**Comment by HFPasfho** [comment]
Well, I won't submit anything new then for a while. Maybe ever. Also let me advise you to periodically close garbage issues or disable issues entirely because this project is already buried in them. I wish you success in development and good luck with this project! I hope android version will be constantly improved!
