### ISSUE TITLE
About asia region and chinese lang

### ISSUE THREAD

**Issue by Croden1999** [Vita3K/Vita3K-Android#372]
if enable the Asia region font support or switch Chinese language on Adreno device, they're couldn't display normal text and fonts, hoping to lower the dpi of the font.
please Mr. @Macdu check it. 🙏🏻🙏🏻🙏🏻

**Comment by Croden1999** [comment]
> if enable the Asia region font support or switch Chinese language on Adreno device, they're couldn't display normal text and fonts, hoping to lower the dpi of the font, please Mr. Macdu check it.

**Comment by Croden1999** [comment]
like this, in version 5 to 7
````
sys-lang: 10
asia-font-support: true
````
![](https://github.com/Vita3K/Vita3K-Android/assets/61804715/25bd4ea3-18aa-48ed-9015-e57d72537ead)

**Comment by segfault-bilibili** [comment]
https://github.com/Vita3K/Vita3K/issues/2942

**Comment by Croden1999** [comment]
[暂时]如果使用中文的用户可以浏览这个链接解决文字不显示的问题
https://tieba.baidu.com/p/8436688470

**Comment by Croden1999** [comment]
is fixed, but please do not check Asia Region of Font Support
