### ISSUE TITLE
Gradually gets slower

### ISSUE THREAD

**Issue by Kodachiyo** [Vita3K/Vita3K-Android#419]
Maybe a few optimizations for Mali? First few minutes, games run smooth at 60 fps, then after 5 to 10 minutes, it slows down at lot. But that's only on the game screen, as pause menus would continue running smooth at 60 fps.

Also, said in game screens would also look to run at 60 fps when I go to gui mode while running a game (the mode where game keeps running with gui on the top screen visible, but controller overlay inaccessible.) then goes to back low fps when I press continue on emulator pause screen.

Also, if only yer interested, you could go try for a "kind of a" budget phone that's been out only recent years I think, for Mali gpu testing. Something similar to mine which is just below a hundred dollars, around 88 dollars or so I think. Yeah it's not high end, but it does seem to be kind of cool for gaming when it comes to low budget phones.

Mine is 4gb ram expandable to 8gb using internal memory, 128 rom, Android V12, Octacore.
CPU: UMS9230 (T606), or model shows to be Spreadtrum T616 when I try using gpu checker.
GPU: MALI-G57
If yer interested, It's TECNOSpark10c and Tecno seems to be relatively cheap on market

I know its probably cause it's not a really powerful Mali driver, but it can run AetherS2 almost seamlessly.

**Comment by hainam1993** [comment]
I have the same problem when playing dragon's crown and my phone is red magic 8 pro which is powered by the current most powerful chipset for android.

**Comment by Kodachiyo** [comment]
> I have the same problem when playing dragon's crown and my phone is red magic 8 pro which is powered by the current most powerful chipset for android.

Redmagic has snapdragon, if I'm not mistaken?Have you tried changing custom drivers? Turnip and such? I heard it fixes a bunch of performance issues with snapdragon.

**Comment by hainam1993** [comment]
Turnip version for snap gen 1 or above doesnt make anything better,other stock drivers even freeze the game upon launching or display pitch black screen as soon as my character leave the tavern.
Got the same problem with Muramasa rebirth except that it does not slow down but outright crashes and automatically close the app right after the encounter with very first horde of enemies at the start of the game
