### ISSUE TITLE
Unable to install game

### ISSUE THREAD

**Issue by Cruzejer123** [Vita3K/Vita3K-Android#480]
Format: NoNpDrm

Game: Angry Birds Trilogy

I try so hard to get it to install the game ( I have previous success with mortal kombat ) but Vita 3k just crashes every time and again x3 and I try every method I can think of but it's just not installing I think it's my install of Vita 3k is bugged can someone help me.

**Comment by Kodachiyo** [comment]
Check game compatibilities, then maybe try older builds of vita 3k, then whether it works or not, give another heads up to the devs so it can be classified whether the game works in older versions, or doesn't install at all

Also, try redumping the game or whatnot, if it helps
