### ISSUE TITLE
Cold steel 2 crash after loading screen and logo

### ISSUE THREAD

**Issue by Alphonsokurukuchu** [Vita3K/Vita3K-Android#503]
This is a very strange issue because it doesn't crash for everyone and every device. It crashes in my phone with sd 730g(6gb ram, Android 12) while it runs perfectly fine in my tab with sd 865+(6gb ram, Android 13). It also runs fine for users with Mali GPU. It works with opengl but with a lot of graphic and performance issues
I have so far tried 
-using various different drivers of both proprietary and turnip
-various combination of settings including other memory mapping, I use lowest graphic settings with 1x resolution and 1x anisotropic filter 

The game crashes right after showing xseed and falcom logo

**Comment by saggybrown** [comment]
Just curious you mention openGL which I noticed it works but I obviously unplayable due to glitches. Are you saying it works on Vulkan on some devices?

**Comment by Alphonsokurukuchu** [comment]
> Just curious you mention openGL which I noticed it works but I obviously unplayable due to glitches. Are you saying it works on Vulkan on some devices?

Yep. It works on some devices with Vulkan(Like my tab with sd865+, some people with Mali GPU and few others randomly I see running the game), but for many it just crashes after the logo and stuff, not even reaching the main menu

**Comment by Alphonsokurukuchu** [comment]
Resolved with v10
