### ISSUE TITLE
where is /ux0/app folder?

### ISSUE THREAD

**Issue by MakaiHanta** [Vita3K/Vita3K-Android#627]
Where is the folder with installed games?

**Comment by shadow-nero** [comment]
It is in the Android/data/org.vita3k.emulator/files/vita
If you are above Android 12 you will not be able to access this folder as easily.

**Comment by MakaiHanta** [comment]
> It is in the Android/data/org.vita3k.emulator/files/vita If you are above Android 12 you will not be able to access this folder as easily.

Yep, Pixel 7 file manager has the data folder empty even though hidden folders are enabled. Figured I'd download some other file manager. The only file manager that allowed me to access the vita3k directory is "Files" https://play.google.com/store/apps/details?id=com.marc.files . This directory shows up there as a third-party drive
